language: python
services:
- rabbitmq
node_js:
- '0.10'
before_install:
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
install:
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
- pip install -r requirements.pip
before_script:
- mosquitto -d
script:
- npm test
